Fix for error when replacing ProductGridContainer via Components.API (#3382)
This change fixes issue 3382.

The reason for the error is that a re-instantiation through the
Meteor.Tracker reruns the constructor of ProductGridContainer without
passing the properties `props.productsByKey` and `props.productIds`
which results in the error:

This is because Tracker instantiation does not occur via code in
products.js, line 69 :
```
<Components.ProductGrid
        productsByKey={productsByKey || {}}
        productIds={getIds({ tags: products })}
        canEdit={Reaction.hasPermission("createProduct")}
        products={products}
      />
```
which is used the first time the component is created.

The solution is to use a reactive composer that injects the properties
during each tracker run.

  TypeError: Cannot read property 'map' of undefined